# ┌──────────────────────────────────────┐
# │ ░█▀█░█░░░█▀█░█▀▀░█▀▄░▀█▀░▀█▀░▀█▀░█░█ │
# │ ░█▀█░█░░░█▀█░█░░░█▀▄░░█░░░█░░░█░░░█░ │
# │ ░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░░░▀░░░▀░ │
# └──────────────────────────────────────┘

[general]
live_config_reload = true
import = [ "~/.config/alacritty/themes/dark.toml" ]

[window]
padding = { x = 10, y = 10 }
opacity = 0.8

[font]
size = 9
normal = { family = "JetBrainsMono NFP", style = "SemiBold" }
bold = { family = "JetBrainsMono NFP", style = "ExtraBold" }
italic = { family = "JetBrainsMono NFP", style = "SemiBold Italic" }
bold_italic = { family = "JetBrainsMono NFP", style = "ExtraBold Italic" }

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_timeout = 0
